export { default as HomePage } from "./HomePage";
export { AreasPage } from "./resources/AreasPage";
export { AvaliacoesPage } from "./resources/AvaliacoesPage";
export { AvaliadoresPage } from "./resources/AvaliadoresPage";
export { EscolasPage } from "./resources/EscolasPage";
export { EventosPage } from "./resources/EventosPage";
export { EstudantesPage } from "./resources/EstudantesPage";
export { PerguntasPage } from "./resources/PerguntasPage";
export { PremiacoesPage } from "./resources/PremiacoesPage";
export { ProjetosPage } from "./resources/ProjetosPage";
export { UsuariosPage } from "./resources/UsuariosPage";
export { DocumentosPage } from "./configuracoes/DocumentosPage";
export { DocumentosConfiguracoesPage } from "./configuracoes/DocumentosConfiguracoesPage"; 