<?php

namespace Database\Seeders;

use App\Models\Question;
use Carbon\Carbon;
use Illuminate\Database\Seeder;

class QuestionSeeder extends Seeder
{
    public function run()
    {
        $questions = [
            [
                'id' => 6,
                'scientific_text' => 'Problema/hipótese: delimitação do tema, relação hipótese/problema/objetivo; clareza na formulação; originalidade; relevância social.',
                'technological_text' => 'Problema/hipótese: delimitação do tema, relação hipótese/problema/objetivo; clareza na formulação; originalidade; relevância social.',
                'type' => 1,
                'number_alternatives' => 10,
                'created_at' => Carbon::parse('2024-10-02 13:24:44'),
                'updated_at' => Carbon::parse('2024-10-02 13:24:44'),
                'deleted_at' => null,
            ],
            [
                'id' => 7,
                'scientific_text' => 'Problema: definição clara do problema; alternativas de solução relacionando com teorias e conceitos científicos; originalidade; relevância social.',
                'technological_text' => 'Problema: definição clara do problema; alternativas de solução relacionando com teorias e conceitos tecnológicos; originalidade; relevância social.',
                'type' => 1,
                'number_alternatives' => 10,
                'created_at' => Carbon::parse('2024-10-02 13:25:22'),
                'updated_at' => Carbon::parse('2024-10-02 13:25:22'),
                'deleted_at' => null,
            ],
            [
                'id' => 8,
                'scientific_text' => 'Coleta de dados/metodologia: metodologia utilizada; seleção/aplicação de instrumentos de coleta; seleção da amostra (amostragem); análise e interpretação dos dados.',
                'technological_text' => 'Coleta de dados/metodologia: metodologia utilizada; seleção/aplicação de instrumentos de coleta; seleção da amostra (amostragem); análise e interpretação dos dados.',
                'type' => 1,
                'number_alternatives' => 10,
                'created_at' => Carbon::parse('2024-10-02 13:25:54'),
                'updated_at' => Carbon::parse('2024-10-02 13:25:54'),
                'deleted_at' => null,
            ],
            [
                'id' => 9,
                'scientific_text' => 'Elaboração do projeto/Metodologia: conhecimento científico; materiais e métodos; análises e interpretações de dados.',
                'technological_text' => 'Elaboração do projeto/Metodologia: conhecimento tecnológico; materiais e métodos; análises e interpretações de dados.',
                'type' => 1,
                'number_alternatives' => 10,
                'created_at' => Carbon::parse('2024-10-02 13:26:11'),
                'updated_at' => Carbon::parse('2024-10-02 13:26:11'),
                'deleted_at' => null,
            ],
            [
                'id' => 10,
                'scientific_text' => 'Considerações Finais: relação com o problema e objetivos; pertinência com os resultados; análise a partir das hipóteses elaboradas.',
                'technological_text' => 'Considerações Finais: relação com o problema e objetivos; pertinência com os resultados; análise a partir das hipóteses elaboradas.',
                'type' => 1,
                'number_alternatives' => 20,
                'created_at' => Carbon::parse('2024-10-02 13:26:30'),
                'updated_at' => Carbon::parse('2024-10-02 13:26:30'),
                'deleted_at' => null,
            ],
            [
                'id' => 11,
                'scientific_text' => 'Resultados: apresentação clara dos resultados; análise dos dados; interpretação dos resultados; relação com a literatura científica.',
                'technological_text' => 'Produto/processo: definição do produto e/ou processo; construção do protótipo e/ou gestão de processo; resposta à necessidade inicial; viabilidade técnica do projeto/custo-benefício; nível de inovação/ impacto técnico-científico.',
                'type' => 1,
                'number_alternatives' => 10,
                'created_at' => Carbon::parse('2024-10-02 13:26:44'),
                'updated_at' => Carbon::parse('2024-10-02 13:26:44'),
                'deleted_at' => null,
            ],
            [
                'id' => 12,
                'scientific_text' => 'Banner: equilíbrio e distribuição entre textos e figuras, clareza no texto e qualidade das figuras.',
                'technological_text' => 'Banner: equilíbrio e distribuição entre textos e figuras, clareza no texto e qualidade das figuras.',
                'type' => 1,
                'number_alternatives' => 20,
                'created_at' => Carbon::parse('2024-10-02 13:27:48'),
                'updated_at' => Carbon::parse('2024-10-02 13:27:48'),
                'deleted_at' => null,
            ],
            [
                'id' => 13,
                'scientific_text' => 'Banner: equilíbrio e distribuição entre textos e figuras, clareza no texto e qualidade das figuras.',
                'technological_text' => 'Banner: equilíbrio e distribuição entre textos e figuras, clareza no texto e qualidade das figuras.',
                'type' => 1,
                'number_alternatives' => 20,
                'created_at' => Carbon::parse('2024-10-02 13:27:53'),
                'updated_at' => Carbon::parse('2024-10-02 13:27:53'),
                'deleted_at' => null,
            ],
            [
                'id' => 14,
                'scientific_text' => 'Relatório: detalhamento do trabalho desenvolvido',
                'technological_text' => 'Relatório: detalhamento do trabalho desenvolvido',
                'type' => 1,
                'number_alternatives' => 20,
                'created_at' => Carbon::parse('2024-10-02 13:28:16'),
                'updated_at' => Carbon::parse('2024-10-02 13:28:16'),
                'deleted_at' => null,
            ],
            [
                'id' => 15,
                'scientific_text' => 'Relatório: detalhamento do trabalho desenvolvido',
                'technological_text' => 'Relatório: detalhamento do trabalho desenvolvido',
                'type' => 1,
                'number_alternatives' => 20,
                'created_at' => Carbon::parse('2024-10-02 13:28:21'),
                'updated_at' => Carbon::parse('2024-10-02 13:28:21'),
                'deleted_at' => null,
            ],
            [
                'id' => 16,
                'scientific_text' => 'Resumo Expandido: clareza na redação; linguagem científica; conteúdo',
                'technological_text' => 'Resumo Expandido: clareza na redação; linguagem tecnológica; conteúdo',
                'type' => 1,
                'number_alternatives' => 20,
                'created_at' => Carbon::parse('2024-10-02 13:28:34'),
                'updated_at' => Carbon::parse('2024-10-02 13:28:34'),
                'deleted_at' => null,
            ],
            [
                'id' => 17,
                'scientific_text' => 'Resumo Expandido: clareza na redação; linguagem científica; conteúdo',
                'technological_text' => 'Resumo Expandido: clareza na redação; linguagem tecnológica; conteúdo',
                'type' => 1,
                'number_alternatives' => 20,
                'created_at' => Carbon::parse('2024-10-02 13:28:39'),
                'updated_at' => Carbon::parse('2024-10-02 13:28:39'),
                'deleted_at' => null,
            ],
            [
                'id' => 18,
                'scientific_text' => 'Caderno de campo (diário de bordo): registros dos procedimentos e datas.',
                'technological_text' => 'Caderno de campo (diário de bordo): registros dos procedimentos e datas.',
                'type' => 1,
                'number_alternatives' => 20,
                'created_at' => Carbon::parse('2024-10-02 13:28:51'),
                'updated_at' => Carbon::parse('2024-10-02 13:28:51'),
                'deleted_at' => null,
            ],
            [
                'id' => 19,
                'scientific_text' => 'Caderno de campo (diário de bordo): registros dos procedimentos e datas.',
                'technological_text' => 'Caderno de campo (diário de bordo): registros dos procedimentos e datas.',
                'type' => 1,
                'number_alternatives' => 20,
                'created_at' => Carbon::parse('2024-10-02 13:28:55'),
                'updated_at' => Carbon::parse('2024-10-02 13:28:55'),
                'deleted_at' => null,
            ],
            [
                'id' => 20,
                'scientific_text' => 'Impacto socioambiental: o trabalho apresenta abordagem e resultados que colaboram para o desenvolvimento de uma sociedade mais igualitária e sustentável?',
                'technological_text' => 'Impacto socioambiental: o trabalho apresenta abordagem e resultados que colaboram para o desenvolvimento de uma sociedade mais igualitária e sustentável?',
                'type' => 1,
                'number_alternatives' => 20,
                'created_at' => Carbon::parse('2024-10-02 13:29:08'),
                'updated_at' => Carbon::parse('2024-10-02 13:29:08'),
                'deleted_at' => null,
            ],
            [
                'id' => 21,
                'scientific_text' => 'Impacto socioambiental: o trabalho apresenta abordagem e resultados que colaboram para o desenvolvimento de uma sociedade mais igualitária e sustentável?',
                'technological_text' => 'Impacto socioambiental: o trabalho apresenta abordagem e resultados que colaboram para o desenvolvimento de uma sociedade mais igualitária e sustentável?',
                'type' => 1,
                'number_alternatives' => 20,
                'created_at' => Carbon::parse('2024-10-02 13:29:12'),
                'updated_at' => Carbon::parse('2024-10-02 13:29:12'),
                'deleted_at' => null,
            ],
            [
                'id' => 22,
                'scientific_text' => 'A apresentação é atrativa e traz uma identidade visual?',
                'technological_text' => 'A apresentação é atrativa e traz uma identidade visual?',
                'type' => 1,
                'number_alternatives' => 20,
                'created_at' => Carbon::parse('2024-10-02 13:29:26'),
                'updated_at' => Carbon::parse('2024-10-02 13:29:26'),
                'deleted_at' => null,
            ],
            [
                'id' => 23,
                'scientific_text' => 'A apresentação é atrativa e traz uma identidade visual?',
                'technological_text' => 'A apresentação é atrativa e traz uma identidade visual?',
                'type' => 1,
                'number_alternatives' => 20,
                'created_at' => Carbon::parse('2024-10-02 13:29:31'),
                'updated_at' => Carbon::parse('2024-10-02 13:29:31'),
                'deleted_at' => null,
            ],
            [
                'id' => 24,
                'scientific_text' => 'Os autores/mentores do trabalho foram sempre respeitados?',
                'technological_text' => 'Os autores/mentores do trabalho foram sempre respeitados?',
                'type' => 1,
                'number_alternatives' => 20,
                'created_at' => Carbon::parse('2024-10-02 13:29:43'),
                'updated_at' => Carbon::parse('2024-10-02 13:29:43'),
                'deleted_at' => null,
            ],
            [
                'id' => 25,
                'scientific_text' => 'Os autores/mentores do trabalho foram sempre respeitados?',
                'technological_text' => 'Os autores/mentores do trabalho foram sempre respeitados?',
                'type' => 1,
                'number_alternatives' => 20,
                'created_at' => Carbon::parse('2024-10-02 13:29:47'),
                'updated_at' => Carbon::parse('2024-10-02 13:29:47'),
                'deleted_at' => null,
            ],
            [
                'id' => 26,
                'scientific_text' => 'Os autores/mentores do trabalho foram sempre respeitados?',
                'technological_text' => 'Os autores/mentores do trabalho foram sempre respeitados?',
                'type' => 1,
                'number_alternatives' => 20,
                'created_at' => Carbon::parse('2024-10-02 13:29:50'),
                'updated_at' => Carbon::parse('2024-10-02 13:29:50'),
                'deleted_at' => null,
            ],
            [
                'id' => 27,
                'scientific_text' => 'Os autores/mentores do trabalho foram sempre respeitados?',
                'technological_text' => 'Os autores/mentores do trabalho foram sempre respeitados?',
                'type' => 1,
                'number_alternatives' => 20,
                'created_at' => Carbon::parse('2024-10-02 13:29:55'),
                'updated_at' => Carbon::parse('2024-10-02 13:29:55'),
                'deleted_at' => null,
            ],
        ];

        foreach ($questions as $question) {
            Question::create($question);
        }
    }
}
